### Authorization by token
GET http://localhost:8080/groups/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtYWlsIjoiYW50b2luZUBiYXR0dXQuZGV2IiwicGFzc3dvcmQiOiJ0b3RvIiwiaWF0IjoxNjg0MDk4Mjc2fQ.ovOqmEbSZttrmMl5Rd7M5K3Pl3oJDLDkSkq9cGaSljc


### Create group
POST http://localhost:8080/groups/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtYWlsIjoiYW50b2luZUBiYXR0dXQuZGV2IiwicGFzc3dvcmQiOiJ0b3RvIiwiaWF0IjoxNjg0MDk4Mjc2fQ.ovOqmEbSZttrmMl5Rd7M5K3Pl3oJDLDkSkq9cGaSljc

{
  "name": "coucou",
  "color": "#FFFFF"
}

### Update group
PATCH http://localhost:8080/groups/6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtYWlsIjoiYW50b2luZUBiYXR0dXQuZGV2IiwicGFzc3dvcmQiOiJ0b3RvIiwiaWF0IjoxNjg0MDk4Mjc2fQ.ovOqmEbSZttrmMl5Rd7M5K3Pl3oJDLDkSkq9cGaSljc

{
  "color": "#FFFFFEEYY"
}

### Delete group
DELETE http://localhost:8080/groups/6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtYWlsIjoiYW50b2luZUBiYXR0dXQuZGV2IiwicGFzc3dvcmQiOiJ0b3RvIiwiaWF0IjoxNjg0MDk4Mjc2fQ.ovOqmEbSZttrmMl5Rd7M5K3Pl3oJDLDkSkq9cGaSljc

### Get group by id
GET http://localhost:8080/groups/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtYWlsIjoiYW50b2luZUBiYXR0dXQuZGV2IiwicGFzc3dvcmQiOiJ0b3RvIiwiaWF0IjoxNjg0MDk4Mjc2fQ.ovOqmEbSZttrmMl5Rd7M5K3Pl3oJDLDkSkq9cGaSljc
