### Authorization by token
GET http://localhost:8080/links/
Authorization: Bearer 


### Create group
POST http://localhost:8080/links/
Content-Type: application/json
Authorization: Bearer 

{
  "name": "github",
  "redirect": "https://github.com"
}

### Update group
PATCH http://localhost:8080/links/2
Content-Type: application/json
Authorization: Bearer 

{
  "method": "subdomain"
}

### Delete group
DELETE http://localhost:8080/links/2
Content-Type: application/json
Authorization: Bearer 

### Get group by id
GET http://localhost:8080/links/2
Content-Type: application/json
Authorization: Bearer 
